
public enum GuidesCategories
{
    CATEGORY_BASIC_INFO = 0,
    CATEGORY_INFO_ITEMS = 1,
    CATEGORY_CUSTOM_ITEMS = 2,
    CATEGORY_EVENT = 3,
    CATEGORY_SERVER_INFO = 4,
    CATEGORY_TUTORIALS = 5,
    CATEGORY_EXTRA_INFO = 6,
}